# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Resources
    url: '#portfolio'
    weight: 20
  - name: Abstract
    url: '#abstract'
    weight: 30
  - name: About
    url: '#info'
    weight: 40
  - name: Authors
    url: '#authors'
    weight: 50
  - name: Acknowledgements
    url: '#acknowledgements'
    weight: 60
  - name: Citation
    url: '#citation'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
